default_config:

logger:
  default: info
  logs:
    custom_components.esp_rfid_v3: debug

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12

frontend:
  themes: !include_dir_merge_named themes
